import HasslesStyleSurvey from "../../surveytypes/HasslesStyleSurvey";

const HasslesScreen = ({navigation}) => {

    const survey = 
        <HasslesStyleSurvey 

            questionnaireNumber={3}

            goHome={() => navigation.navigate('Home')}

            scales={[
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
            ]}

            values={[
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
                [0,1,2,3],
            ]}

            qs={[
                "Your child(ren)",
                "Your parents or parents-in-law",
                "Other relative(s)",
                "Your spouse",
                "Time spent with family",
                "Health or well-being of a family member",
                "Sex",

                "Intimacy",
                "Family-related obligations",
                "Your friend(s)",
                "Fellow workers",
                "Clients, customers, patients, etc.",
                "Your supervisor or employer",
                "The nature of your work",
                "Your work load",
                "Your job security",
                "Meeting deadlines or goals on the job",
                "Enough money for necessities (e.g. food, clothing, housing, health care, taxes, insurance)",
                "Enough money for education",
                "Enough money for emergencies",
                "Enough money for extras (e.g. entertainment, recreation, vacations)",
                "Financial care for someone who doesn't live with you",
                "Investments",
                "Your smoking",
                "Your drinking",
                "Mood-altering drugs",
                "Your physical appearance",
                "Contraception",
                "Exercise(s)",
                "Your medical care",

                "Your health",
                "Your physical appearance",
                "The weather",
                "News events",
                "Your environment (e.g. quality of air, noise level, greenery)",
                "Political or social isssues",
                "Your neighborhood (e.g. neighbors, setting",
                "Conserving (gas, electricity, water, gasoline, etc.)",
                "Pets",
                "Cooking",
                "Houswork",
                "Home repairs",
                "Yardwork",
                "Car maintenance",
                "Taking care of paperwork (e.g. paying bills, filling out forms)",
                "Home entertainment (e.g. TV, music, reading)",
                "Amount of free time",
                "Recreation and entertainment outside the home (e.g. movies, sports, eating out, walking)",
                "Eating (at home)",
                "Church or community organizations",
                "Legal matters",
                "Being organized",
                "Social commitments",
            ]}

        
        />

    return survey;
}
 
export default HasslesScreen;